baseURL = "https://io-oi.me/"
theme = "meme"
# https://en.wikipedia.org/wiki/Language_localisation
# https://www.zhihu.com/question/21980689
defaultContentLanguage = "zh-cn"

defaultContentLanguageInSubdir = false

enableGitInfo = true

pluralizeListTitles = false

summaryLength = 42

enableRobotsTXT = true

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

enableEmoji = true

footnoteReturnLinkContents = "↩"

paginate = 5

[related]
threshold = 80
includeNewer = true
toLower = true
[[related.indices]]
name = "categories"
weight = 100
[[related.indices]]
name = "tags"
weight = 95
[[related.indices]]
name = "keywords"
weight = 90
[[related.indices]]
name = "date"
weight = 10
pattern = "2006"

[frontmatter]
lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

[blackfriday]
smartypants = false
fractions = false
hrefTargetBlank = true
extensionsmask = ["hardLineBreak", "backslashLineBreak"]

[languages.zh-cn]
languageName = "中文"
contentDir = "content/zh"
weight = 1
languageCode = "zh-CN"
hasCJKLanguage= true
title = "reuixiy"
copyright = "在保留本文作者及本文链接的前提下，非商业用途随意转载分享。"
[languages.zh-cn.params]
lineHeight = 2

[languages.en-us]
languageName = "English"
contentDir = "content/en"
weight = 2
languageCode = "en-US"
title = "reuixiy"
copyright = ""
[languages.en-us.taxonomies]
# category = "categories"
# tag = "tags"
# name = "names"
[[languages.en-us.menu.home]]
url = "/en-us/about/"
weight = 3
pre = "internal"
post = "user-circle"
identifier = "about"
[languages.en-us.params]
homePoetry = ["In the dark night", "Longing for a light of care", "In the daylight", "Desiring for the swallow of a black hole", "’Cause curiosity — seeks for what’s in the darkness"]
lineHeight = 1.618
enableSmallCap = true
postWidth = 28
enableJustify = false
enableChinesePunctuationGlyphCorrection = false
customFooter = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"

# uglyURLs = true

[permalinks]
# life = "/:sections/:slug/"
# tech = "/:sections/:slug/"
# categories = "/categories/:slug/"
tags = "/tags/:slug/"

[taxonomies]
# category = "categories"
tag = "tags"
# name = "names"

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[outputFormats.SectionsAtom]
mediaType = "application/atom+xml"
baseName = "atom"

[outputFormats.SectionsRSS]
mediaType = "application/rss+xml"
baseName = "rss"
# [outputFormats.NoUglyHTML]
# mediaType = "text/html"
# noUgly = "true"
# [outputFormats.NoUglyRSS]
# mediaType = "application/rss+xml"
# noUgly = "true"
# [outputFormats.NoUglyAtom]
# mediaType = "application/atom+xml"
# baseName = "atom"
# noUgly = "true"

# [outputs]
# page = ["HTML"]
# home = ["HTML", "Atom", "RSS", "SectionsAtom", "SectionsRSS"]
# section = ["NoUglyHTML", "NoUglyRSS", "NoUglyAtom"]
# # NOT Work, see: https://github.com/gohugoio/hugo/issues/4528
# # taxonomyTerm = ["HTML"]
# taxonomy = ["NoUglyHTML", "NoUglyRSS"]

[outputs]
page = ["HTML"]
home = ["HTML", "SectionsAtom", "SectionsRSS"]
section = ["HTML"]
# NOT Work, see: https://github.com/gohugoio/hugo/issues/4528
# taxonomyTerm = ["HTML"]
taxonomy = ["HTML"]

[author]
name = "reuixiy"
email = "reuixiy@gmail.com"
# Your description, Markdown supported, this theme noly
motto = "Viva La Vida"
# Your avatar, URL, this theme noly
avatar = "/icons/apple-touch-icon.png"
# URL, this theme noly, Default: baseURL
website = "https://io-oi.me/"
twitter = "reuixiy"
facebook = "reuixiy"

# RSS & Atom limit
[services.rss]
limit = -1

# [[menu.main]]
# url = "/home/"
# name = "首页"
# weight = 1
# pre = "internal"
# post = "home"
# identifier = "home"

# [[menu.main]]
# url = "/archives/"
# name = "归档"
# weight = 2
# pre = "internal"
# post = "archive"
# identifier = "archives"

# [[menu.main]]
# url = "/life/"
# name = "生活"
# weight = 3
# pre = "internal"
# post = "grav"
# identifier = "life"

# [[menu.main]]
# url = "/tech/"
# name = "技术"
# weight = 4
# pre = "internal"
# post = "wpexplorer"
# identifier = "tech"

# [[menu.main]]
# url = "/categories/"
# name = "categories"
# weight = 5
# pre = "internal"
# post = "th"
# identifier = "categories"

# [[menu.main]]
# url = "/tags/"
# name = "tags"
# weight = 6
# pre = "internal"
# post = "tags"
# identifier = "tags"

# [[menu.main]]
# url = "/about/"
# name = "about"
# weight = 7
# pre = "internal"
# post = "user-circle"
# identifier = "about"

[[menu.home]]
url = "/life/"
weight = 1
pre = "internal"
post = "grav"
identifier = "life"

[[menu.home]]
url = "/tech/"
weight = 2
pre = "internal"
post = "wpexplorer"
identifier = "tech"

[[menu.home]]
url = "/about/"
weight = 3
pre = "internal"
post = "user-circle"
identifier = "about"

# [[menu.home]]
# url = "/life/"
# name = "Life"
# weight = 1
# pre = "internal"
# identifier = "life"

# [[menu.home]]
# url = "https://t.me/yixiuer"
# name = "Telegram"
# weight = 2
# pre = "external"
# identifier = "telegram"

# [[menu.home]]
# url = "/atom.xml"
# name = "Feed"
# weight = 3
# pre = "external"
# identifier = "feed"

[[menu.socials]]
url = "https://github.com/reuixiy"
name = "GitHub"
weight = 1
pre = "external"
identifier = "github"

[[menu.socials]]
url = "https://twitter.com/reuixiy"
name = "Twitter"
weight = 2
pre = "external"
identifier = "twitter"

[[menu.socials]]
url = "https://music.163.com/user/home?id=86590096"
name = "Music"
weight = 3
pre = "external"
identifier = "music"

[[menu.links]]
url = "/"
name = "HOME"
weight = 1
pre = "internal"
identifier = "home"

[[menu.links]]
url = "/coldplay/"
name = "Coldplay"
weight = 2
pre = "internal"
identifier = "coldplay"

[[menu.links]]
url = "/atom.xml"
name = "Feed"
weight = 3
pre = "external"
identifier = "feed"

[params]
enableHeader = true
displayHeaderInHome = true

enableMenu = false
displayMenuInHome = false

# Use for Header, If true, Please put your SVG brand image to `svg.toml`.
# If false, will use your Site Title as fallback.
# Unit: px
siteBrandSVG = true
siteBrandSVGWidth = 250
siteBrandSVGHeight = 100
siteBrandSVGFill = "#fff"

# Unit: em
siteBrandFontSize = 5
siteBrandFontColor = "#fff"

# siteBrandBackgroundColor = "hsl(240, 8%, 12%)"
siteBrandBackgroundImage = "linear-gradient(90deg, #f79533 0, #f37055 15%, #ef4e7b 30%, #a166ab 44%, #5073b8 58%, #1098ad 72%, #07b39b 86%, #6dba82 100%)"

# poetry, footage, posts
homeLayout = "poetry"
# Layout poetry settings
# Markdown supported
homePoetry = ["暗夜中", "渴望一束光的关怀", "在白天", "却更渴望黑洞的吞噬", "因为好奇心，想看看黑暗中有什么"]
# Unit: em
homeLinksPadding = 1
# Layout footage settings
homePoster = "/images/reflection-of-tree-at-night-10s-720p.jpg"
homeVideoWebm = "/videos/reflection-of-tree-at-night-10s-720p.webm"
homeVideoMp4 = "/videos/reflection-of-tree-at-night-10s-720p.mp4"
homeLogo = "/icons/android-chrome-512x512.png"
homeLogoLink = "/life/"
homeTitle = "一休儿的哲学博客"
homeMotto = "易·象·辞"
homeDescription = "一个关于哲学的博客，目标是构建一个宏大的体系"
homeKeywords = "关键词：真理、形而上学、哲学、物理、诗歌、酒神、尼采、《查拉图斯特拉如是说》、神话、未来、科幻、赛博朋克、反乌托邦、去中心化、开源、太空"
homeLinksDelimiter = "·"

# URL, For JSON-LD, Twitter Cards, Open Graph
siteLogo = "/icons/apple-touch-icon.png"
# For HTML meta
siteDescription = "这是 reuixiy 的生活与技术博客！怎么记住 reuixiy 呢？其实就是「一休儿」的拼音，只不过顺序是从右往左……"
# If not set, will use site all taxonomies term as default
siteKeywords = []
# Keep this format, change the number
siteCreatedTime = "2017-05-27T15:13:14+08:00"
# If you enable `twitterCards`, then add your Twitter username
siteTwitter = "reuixiy"
# If you enable `openGraph`, then add your Facebook username
siteFacebook = "reuixiy"

# Category
# sections or categories
# Note: You must delete `categories` in `taxonomies` if you set `sections`.
categoryBy = "sections"

# Categories Page
# Note: You can NOT disable tree if you set categoryBy equal to `sections`.
enableTree = true
displayPosts = true
displayPostsCount = true

# Tags
enableTagCloud = true
fontUnit = "em"
largestFontSize = 2.5
smallestFontSize = 1

# Unit: em
# You can leave it empty ("") to fallback to default value: 42
listWidth = 36
displayListTitle = true
# https://gohugo.io/functions/format/
listDateFormat = "2006-01-02"
# left / right
listDatePosition = "right"
groupByMonth = false
chineseZodiac = true
i18nYear = false
i18nMonth = true

# Taxonomy List
displayTaxonomyTermCount = true

# Overwrite Hugo’s default value
mainSections = ["life", "tech"]

# Post Sections
postSections = ["life", "tech"]

# Feed
feedSections = ["life", "tech"]
# If `true`, will add content to Atom; If `false`, won’t.
# Note: By default, will add summary to Atom as `summary`,
# and if Front Matter have a description, description
# will overwrite summary as `summary`
includeContent = true

# Dark Mode
enableDarkMode = true
defaultTheme = "light"
# Note: If false and enableDarkMode equal to `true`,
# users can still get Dark Mode if their device’s system
# has enabled Dark Mode (`prefers-color-scheme: dark`).
hideThemeToggle = false
hideThemeToggleInHome = false
# Useful for black and white images on a white background.
# Bad for color images. I suggest you set `true` in post’s
# Front Matter instead of here, unless all your images are
# black and white on a white background. Also, you can set
# `true` here and set `false` in Front Matter which will
# overwrite what you have set here.
darkImage = false

# Web App
# https://realfavicongenerator.net/
# Delete browserconfig.xml, android-chrome-192x192.png, favicon-16x16.png, favicon-32x32.png
# Move to ~/blog/static/icons/
# Move favicon.ico site.webmanifest to ~/blog/static/
# Change site.webmanifest to manifest.json
# See https://github.com/w3c/manifest/issues/689
# See https://github.com/OneSignal/OneSignal-Website-SDK/issues/332
# Check and Modify manifest.json (/icons path)
themeColor = "#fff"
themeColorDark = "#000"
safariMaskColor = "#2a6df4"
msApplicationTileColor = "#fff"

# Head Meta, SEO & Social Discovery
# Note that you must set openGraph to `true` if you set twitterCards to `true`,
# or your Twitter Cards info would be incomplete.
jsonLD = true
openGraph = true
twitterCards = true
autoDetectImages = true

# InstantClick
enableInstantClick = true

enableServiceWorker = true

# I suggest you set `katex: true` in post’s Front Matter instead of here
enableKaTeX = false

enableComments = false
enableDisqus = false
disqusShortname = "meme-5"

enableGoogleAnalytics = true
# `gtag` or `analytics`
trackingCodeType = "gtag"
trackingID = "UA-100434861-1"

googleSiteVerification = ""

# https://developers.facebook.com/apps/
# Used for Open Graph
facebookAppID = "436759587050321"

# Post

# Unit: second
duration = 0.5

# HSL color
primaryColorLight = "220, 90%, 56%"
primaryColorDark = "349, 75%, 51%"

# Unit: em
# You can leave it empty ("") to fallback to default value: 42
postWidth = 36

# Do NOT Change this value!
# If one post is not original, set in that post’s Front Matter.
original = true

# Post Description
displayPostDescription = true

# Post Meta
enablePostMeta = false
# Works for home layout `posts` only
enablePostMetaInHome = true
postMetaDateFormat = "January 2"
displayPublishedDate = true
publishedDateIcon = "calendar-alt"
displayModifiedDate = true
modifiedDateIcon = "calendar-check"
# Note that it will not display if the date is zero (not set).
displayExpiredDate = true
expiredDateIcon = "calendar-times"
displayCategory = true
categoryIcon = "folder"
categoryDelimiter = "/"
displayWordCount = true
wordCountIcon = "pencil-alt"
displayReadingTime = true
readingTimeIcon = "clock"

# Table of Contents
enableTOC = false
displayTOCTitle = true
linkHeadingsToTOC = true

# Headings Anchor / Section Sign (Add section sign before headings)
enableHeadingsAnchor = true
# RegEX format, Defaut: 1-6 (1|2|3|4|5|6), h1-h6
headingsOpt = ""
# `anchorIcon` has a higher priority than `anchorSymbol`
# Default: §
anchorSymbol = "#"
anchorIcon = "link"
enableAnchorLink = true
enableAnchorAutoHide = true

# Image / Video
# If true, will replace `title` with caption.
enableCaption = true
captionPrefix = "◎ "

# Image / Video Hosting
# Only support absolute URLs relative to root,
# eg: /../../*.jpg
enableHost = true
hostURL = "https://io-oi.oss-cn-shanghai.aliyuncs.com/"
headAlso = false

# Footnote
# Footnote Ref with Square Brackets `[]`
squareBrackets = true
# If true, will replace `footnoteReturnLinkContents` with icon.
footnoteReturnLinkIcon = "angle-up"
# If true, the automatically added `<hr>` will be deleted.
# (In fact, the separator you added will be removed. This
# will be very useful if you prefer to add `---` to separate
# the content from the footnote in the Markdown file.)
insertHrBySelf = true

# Markdown
# New Markdown Syntax: Emphasis Point `..text..`
enableEmphasisPoint = true

# Typography
# Fonts, Unit: px
fontSize = 16
# Unitless values: use this number multiplied by the element’s font size
# Apply to post paragraph & toc only
lineHeight = 2

# Any value is not set, fallback to `fontFamilyBody` it will.
# If you use SVG as your Site Brand, then leave this value empty.
fontFamilySiteBrand = ""
fontFamilyTitle = "'Cinzel Decorative', 'Noto Serif SC', serif"
fontFamilyHeadings = "'Cinzel Decorative', 'Noto Serif SC', serif"
fontFamilyCode = "'Source Code Pro', 'Noto Serif SC', monospace"
fontFamilyQuote = ""
fontFamilyTOC = ""
fontFamilyCaption = ""
fontFamilyFooter = ""
fontFamilyBody = "'EB Garamond', 'Noto Serif SC', serif"

# https://fonts.google.com/
fontsLink = 'https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,700,700i|Noto+Serif+SC:400,700|Source+Code+Pro:400,400i,700,700i|Cinzel+Decorative:700&display=swap&subset=chinese-simplified'

enableChinesePunctuationGlyphCorrection = true

# Post headings and contents title
enableSmallCap = false

# Post first paragraph
enableDropCap = true
# Every paragraph after `<hr />` or `---` in Markdown
enableDropCapAfterHr = false
deleteHrBeforeDropCap = false

enableParagraphIndent = false
# margin or indent, globe setting, Front Matter: indent
paragraphStyle = "margin"

enableJustify = true

# Post Copyright
enablePostCopyright = true
displayPostCopyright = false

enablePostUpdatedBadge = true
displayUpdatedBadge = false
enableBadgeTitle = true
badgeTitlePrefix = "Updated @ "

enablePostGitInfo = true
repoURL = "https://github.com/reuixiy/io-oi.me"
# or https://github.com/reuixiy/io-oi.me/edit/master
repoEditURL = "https://github.com/reuixiy/io-oi.me/blob/master"
gitIcon = "code-branch"
displayCommitHash = true
displayCommitMessage = true
msgIcon = "info"
displayFeedback = true
feedbackIcon = "question"
feedbackText = "Feedback"
displayEditLink = true
editIcon = "edit"
editText = "Edit Me?"

# Related Posts
enableRelatedPosts = false
relatedPostsNumber = 5
relatedPostsIcon = "plus-circle"

# Post tags
enablePostTags = false
postTagsIcon = "tag"

# Post minimal footer
enableMinimalFooter = true
enableAboutPageMinimalFooter = true

# Post nav
# Note: Designed from a spatial perspective rather than
#       a time perspective like most other themes do.
#       Therefore, you will get a newer post if you click
#       prev on the left; you will get a older post if
#       you click next on the right.
enablePostNav = false
postNavInSection = true

# Syntax Highlight
enableHighlight = true

# Back to Top
enableBackToTop = true
backToTopIcon = "arrow-up"
displayBackToTopInHome = false

# footer
# Note: Home layout `poetry` and `footage`, and 404 page have no footer.
enableFooter = true
displayCopyrightSymbol = true
displaySiteCreatedYear = true
iconBetweenYearAndAuthor = "heart"
iconColor = "#f06292"
iconAnimation = true
displayPoweredBy = true
displaySiteCopyright = false
customFooter = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)"

# Multilingual
enableLangToggle = true
# Display LangToggle only when content is translated
autoHideLangToggle = true
hideLangToggleInHome = false

# 404
fofPoster = "/images/flying-clouds-720p.jpg"
fofVideoWebm = "https://io-oi.oss-cn-shanghai.aliyuncs.com/videos/flying-clouds-720p.webm"
fofVideoMp4 = "https://io-oi.oss-cn-shanghai.aliyuncs.com/videos/flying-clouds-720p.mp4"